using DMS.Domain.Entities;
using DMS.Domain.Enums;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace DMS.Infrastructure.Persistence.Seed;

public static class DatabaseSeeder
{
    public static async Task SeedAsync(ApplicationDbContext dbContext, CancellationToken cancellationToken = default)
    {
        await EnsureAuthSchemaAsync(dbContext, cancellationToken);
        await SeedAdminUserAsync(dbContext, cancellationToken);

        if (await dbContext.Companies.AnyAsync(cancellationToken))
        {
            return;
        }

        var company = new Company
        {
            Code = "NPP001",
            Name = "Default Distributor",
            TaxCode = "0000000000",
            Address = "Ho Chi Minh City",
            Phone = "0900000000",
            Email = "ops@example.com"
        };

        var salesPerson = new SalesPerson
        {
            Code = "SP001",
            Name = "Default Sales",
            Company = company,
            Phone = "0900000001"
        };

        var site = new Site
        {
            Code = "WH001",
            Name = "Main Warehouse",
            Company = company,
            Address = "Ho Chi Minh City"
        };

        var item = new Item
        {
            Code = "ITEM001",
            Name = "Sample Item",
            Unit = "case",
            Barcode = "893000000001",
            Price = 100000m,
            VatRate = 8m
        };

        var customer = new Customer
        {
            Code = "CUS001",
            Name = "Default Retail Customer",
            Company = company,
            SalesPerson = salesPerson,
            Address = "Ho Chi Minh City",
            Phone = "0900000002"
        };

        var inventory = new Inventory
        {
            Site = site,
            Item = item,
            Quantity = 100m,
            ReservedQuantity = 0m
        };

        dbContext.AddRange(company, salesPerson, site, item, customer, inventory);
        await dbContext.SaveChangesAsync(cancellationToken);
    }

    private static async Task EnsureAuthSchemaAsync(ApplicationDbContext dbContext, CancellationToken cancellationToken)
    {
        await dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "SYS_User" (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserName" VARCHAR(100) NOT NULL,
                "PasswordHash" VARCHAR(500) NOT NULL,
                "FullName" VARCHAR(200) NOT NULL,
                "Role" VARCHAR(50) NOT NULL,
                "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
                "CreatedAt" TIMESTAMPTZ NOT NULL,
                "CreatedBy" VARCHAR(100),
                "UpdatedAt" TIMESTAMPTZ,
                "UpdatedBy" VARCHAR(100),
                "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "UX_SYS_User_UserName"
                ON "SYS_User"("UserName");

            CREATE TABLE IF NOT EXISTS "SYS_RefreshToken" (
                "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" BIGINT NOT NULL REFERENCES "SYS_User"("Id") ON DELETE CASCADE,
                "TokenHash" VARCHAR(128) NOT NULL,
                "ExpiresAt" TIMESTAMPTZ NOT NULL,
                "RevokedAt" TIMESTAMPTZ,
                "ReplacedByTokenHash" VARCHAR(128),
                "CreatedAt" TIMESTAMPTZ NOT NULL,
                "CreatedBy" VARCHAR(100),
                "UpdatedAt" TIMESTAMPTZ,
                "UpdatedBy" VARCHAR(100),
                "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "UX_SYS_RefreshToken_TokenHash"
                ON "SYS_RefreshToken"("TokenHash");

            CREATE INDEX IF NOT EXISTS "IX_SYS_RefreshToken_UserId"
                ON "SYS_RefreshToken"("UserId");
            """,
            cancellationToken);
    }

    private static async Task SeedAdminUserAsync(ApplicationDbContext dbContext, CancellationToken cancellationToken)
    {
        if (await dbContext.Users.AnyAsync(x => x.UserName == "admin", cancellationToken))
        {
            return;
        }

        var admin = new ApplicationUser
        {
            UserName = "admin",
            FullName = "System Administrator",
            Role = UserRoles.Admin
        };

        admin.PasswordHash = new PasswordHasher<ApplicationUser>().HashPassword(admin, "Admin@12345");

        dbContext.Users.Add(admin);
        await dbContext.SaveChangesAsync(cancellationToken);
    }
}
