services:
  - type: web
    name: dms-backend-api
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Database__MigrateOnStartup
        value: true
      - key: Database__SeedOnStartup
        value: true
      - key: Jwt__Issuer
        value: DMS.Api
      - key: Jwt__Audience
        value: DMS.Api
      - key: Jwt__Secret
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: dms-postgres
          property: connectionString

databases:
  - name: dms-postgres
    plan: free
